services:
  api:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: api
    volumes:
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - dev

networks:
  dev:
    driver: bridge