name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:27.3.1
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from GitHub secrets
        run: |
          echo "BASE_KEY=$BASE_KEY" >> .env

      - name: Run Docker Compose
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . up --build --force-recreate -d

      - name: Run Unit Tests
        run: |
          docker run --rm tp_eng_software-api python -m unittest tests.unit

      - name: Run Integration Tests
        run: |
          python -m unittest tests.integration

      - name: Shut down Docker Compose services
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . down
  test_windows:
    runs-on: windows-latest

    services:
      docker:
        image: mcr.microsoft.com/windows/servercore:ltsc2022
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from GitHub secrets
        run: |
          echo "BASE_KEY=$BASE_KEY" >> .env

      - name: Run Docker Compose
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . up --build --force-recreate -d

      - name: Run Unit Tests
        run: |
          docker run --rm tp_eng_software-api python -m unittest tests.unit

      - name: Run Integration Tests
        run: |
          python -m unittest tests.integration

      - name: Shut down Docker Compose services
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . down

  test_mac:
    runs-on: macos-latest

    services:
      docker:
        image: docker:27.3.1
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from GitHub secrets
        run: |
          echo "BASE_KEY=$BASE_KEY" >> .env

      - name: Run Docker Compose
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . up --build --force-recreate -d

      - name: Run Unit Tests
        run: |
          docker run --rm tp_eng_software-api python -m unittest tests.unit

      - name: Run Integration Tests
        run: |
          python -m unittest tests.integration

      - name: Shut down Docker Compose services
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . down
