name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker: 
        image: docker:27.3.1
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: |
          docker compose -f docker/docker-compose.yml --project-directory . up --build --force-recreate
          
      - name: Shut down Docker Compose services
        run: |
          docker-compose -f docker/docker-compose.yml --project-directory . down
